/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:07b6a611-3af7-4a4a-913d-43213f79223e",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_3JmoOawJq",
    "aws_user_pools_web_client_id": "43pkuos2n6t9bs78pqqre02uft",
    "oauth": {
        "domain": "milindacademy4e89c2c6-4e89c2c6-staging.auth.us-east-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/,https://milindacademy.com/",
        "redirectSignOut": "http://localhost:3000/,https://milindacademy.com/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"
};


export default awsmobile;
